#APP CONFIGURATION
spring:
  application:
    name: account-service

server:
  port: 7002

#WEB CLIENTS
services:
  transaction-service:
    base-url: http://transaction-service/

#EUREKA CLIENT CONFIGURATION
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:7075/eureka/
    fetch-registry: true
    register-with-eureka: true